[package]
name = "monetary"
version = "0.0.0"
authors = ["Amit Prasad<mail@amitprasad.dev>"]
edition = "2021"
description = "Compile-time type-checked monetary operations"
license = "Apache-2.0"
repository = "https://github.com/AmitPr/monetary"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = "1.5.3"
schemars = "0.8.16"
serde = { version = "1.0.196", features = ["derive"] }
