[package]
name = "monetary"
version = "0.0.0"
authors = ["Amit Prasad<mail@amitprasad.dev>"]
edition = "2021"
description = "Compile-time type-checked monetary operations"
license = "Apache-2.0"
repository = "https://github.com/AmitPr/monetary"

[features]
default = ["serde"]

[dependencies]
cosmwasm-std = { version = "1.5.4", default-features = false }
# schemars = "0.8.16"
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1.0"