[workspace]
members = ["crates/monetary", "crates/monetary-macros"]
authors = ["Amit Prasad<mail@amitprasad.dev>"]
description = "Compile-time type-checked monetary operations"
license = "Apache-2.0"
repository = "https://github.com/AmitPr/monetary"

[workspace.dependencies]
monetary-macros = { path = "crates/monetary-macros" }
monetary = { path = "crates/monetary" }

cosmwasm-std = { version = ">=1, <3" }
serde = { version = "1.0" }
schemars = { version = "0.8" }
serde_json = "1.0"
