[package]
name = "monetary"
version = "0.0.2"
authors = ["Amit Prasad<mail@amitprasad.dev>"]
edition = "2021"
description = "Compile-time type-checked monetary operations"
license = "Apache-2.0"
repository = "https://github.com/AmitPr/monetary"

[features]
default = ["serde", "schemars"]

[dependencies]
cosmwasm-std = { version = ">=1, <3", default-features = false, features = [
    "std",
] }
# schemars = "0.8.16"
serde = { version = "1.0", features = ["derive"], optional = true }
schemars = { version = "0.8", optional = true }

[dev-dependencies]
serde_json = "1.0"
